In [1]:
import pandas as pd
import matplotlib.pyplot as plt

print("Pandas version:", pd.__version__)

Pandas version: 3.0.6

In [5]:
file_path = "Hospital_General_Information.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 5419
Columns: 38

In [6]:
df.head()

,Facility ID,Facility Name,Address,City/Town,State,ZIP Code,County/Parish,Telephone Number,Hospital Type,Hospital Ownership,...,Count of READM Measures Better,Count of READM Measures No Different,Count of READM Measures Worse,READM Group Footnote,Pt Exp Group Measure Count,Count of Facility Pt Exp Measures,Pt Exp Group Footnote,TE Group Measure Count,Count of Facility TE Measures,TE Group Footnote
0,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,Acute Care Hospitals,Government - Hospital District or Authority,...,1,9,1,NaN,15,15,NaN,10,10,NaN
1,010005,MARSHALL MEDICAL CENTERS,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,(256) 593-8310,Acute Care Hospitals,Government - Hospital District or Authority,...,1,8,0,NaN,15,15,NaN,10,10,NaN
2,010006,NORTH ALABAMA MEDICAL CENTER,1701 VETERANS DRIVE,FLORENCE,AL,35630,LAUDERDALE,(256) 768-8400,Acute Care Hospitals,Proprietary,...,1,8,0,NaN,15,15,NaN,10,9,NaN
3,010007,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,COVINGTON,(334) 493-3541,Acute Care Hospitals,Voluntary non-profit - Private,...,0,3,2,NaN,15,5,NaN,10,7,NaN
4,010011,ST. VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,JEFFERSON,(205) 838-3122,Acute Care Hospitals,Voluntary non-profit - Private,...,1,5,2,29.0,15,10,29.0,10,7,29.0

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5419 entries, 0 to 5418
Data columns (total 38 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Facility ID                                       5419 non-null   str
 1   Facility Name                                     5419 non-null   str
 2   Address                                           5419 non-null   str
 3   City/Town                                         5419 non-null   str
 4   State                                             5419 non-null   str
 5   ZIP Code                                          5419 non-null   int64
 6   County/Parish                                     5419 non-null   str
 7   Telephone Number                                  5419 non-null   str
 8   Hospital Type                                     5419 non-null   str
 9   Hospital Ownership                                5419 non-null   str
 10  Emergency Services                                5419 non-null   str
 11  Meets criteria for birthing friendly designation  2263 non-null   str
 12  Hospital overall rating                           5419 non-null   str
 13  Hospital overall rating footnote                  2316 non-null   str
 14  MORT Group Measure Count                          5419 non-null   str
 15  Count of Facility MORT Measures                   5419 non-null   str
 16  Count of MORT Measures Better                     5419 non-null   str
 17  Count of MORT Measures No Different               5419 non-null   str
 18  Count of MORT Measures Worse                      5419 non-null   str
 19  MORT Group Footnote                               1396 non-null   float64
 20  Safety Group Measure Count                        5419 non-null   str
 21  Count of Facility Safety Measures                 5419 non-null   str
 22  Count of Safety Measures Better                   5419 non-null   str
 23  Count of Safety Measures No Different             5419 non-null   str
 24  Count of Safety Measures Worse                    5419 non-null   str
 25  Safety Group Footnote                             2149 non-null   float64
 26  READM Group Measure Count                         5419 non-null   str
 27  Count of Facility READM Measures                  5419 non-null   str
 28  Count of READM Measures Better                    5419 non-null   str
 29  Count of READM Measures No Different              5419 non-null   str
 30  Count of READM Measures Worse                     5419 non-null   str
 31  READM Group Footnote                              1223 non-null   float64
 32  Pt Exp Group Measure Count                        5419 non-null   str
 33  Count of Facility Pt Exp Measures                 5419 non-null   str
 34  Pt Exp Group Footnote                             2016 non-null   float64
 35  TE Group Measure Count                            5419 non-null   str
 36  Count of Facility TE Measures                     5419 non-null   str
 37  TE Group Footnote                                 1008 non-null   float64
dtypes: float64(5), int64(1), str(32)
memory usage: 1.6 MB

In [8]:
df["Hospital overall rating"].value_counts(dropna=False)

Hospital overall rating
Not Available    2245
3                 985
4                 946
2                 661
5                 384
1                 198
Name: count, dtype: int64

In [9]:
df["MORT Group Measure Count"].value_counts(dropna=False)

MORT Group Measure Count
8                4569
Not Available     850
Name: count, dtype: int64

In [10]:
df["READM Group Measure Count"].value_counts(dropna=False)

READM Group Measure Count
11               4569
Not Available     850
Name: count, dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df["Facility ID"].duplicated().sum()

np.int64(0)

In [13]:
df_clean = df.copy()

print("Raw dataset:", df.shape)
print("Working copy:", df_clean.shape)

Raw dataset: (5419, 38)
Working copy: (5419, 38)

In [15]:
df_clean = df.copy()

print("Raw dataset:", df.shape)
print("Working copy:", df_clean.shape)

Raw dataset: (5419, 38)
Working copy: (5419, 38)

In [16]:
not_available_counts = (df_clean == "Not Available").sum()

not_available_counts[not_available_counts > 0].sort_values(ascending=False)

Hospital overall rating                  2245
Count of Safety Measures No Different    2075
Count of Safety Measures Worse           2075
Count of Facility Safety Measures        2075
Count of Safety Measures Better          2075
Count of Facility Pt Exp Measures        1955
Count of Facility MORT Measures          1323
Count of MORT Measures Better            1323
Count of MORT Measures Worse             1323
Count of MORT Measures No Different      1323
Count of READM Measures Worse            1155
Count of Facility READM Measures         1155
Count of READM Measures No Different     1155
Count of READM Measures Better           1155
Count of Facility TE Measures             919
MORT Group Measure Count                  850
READM Group Measure Count                 850
Safety Group Measure Count                850
Pt Exp Group Measure Count                850
TE Group Measure Count                    850
dtype: int64

In [17]:
numeric_candidates = [
    "Hospital overall rating",
    "MORT Group Measure Count",
    "Count of Facility MORT Measures",
    "Count of MORT Measures Better",
    "Count of MORT Measures No Different",
    "Count of MORT Measures Worse",
    "Safety Group Measure Count",
    "Count of Facility Safety Measures",
    "Count of Safety Measures Better",
    "Count of Safety Measures No Different",
    "Count of Safety Measures Worse",
    "READM Group Measure Count",
    "Count of Facility READM Measures",
    "Count of READM Measures Better",
    "Count of READM Measures No Different",
    "Count of READM Measures Worse",
    "Pt Exp Group Measure Count",
    "Count of Facility Pt Exp Measures",
    "TE Group Measure Count",
    "Count of Facility TE Measures"
]

df_clean[numeric_candidates].head()

,Hospital overall rating,MORT Group Measure Count,Count of Facility MORT Measures,Count of MORT Measures Better,Count of MORT Measures No Different,Count of MORT Measures Worse,Safety Group Measure Count,Count of Facility Safety Measures,Count of Safety Measures Better,Count of Safety Measures No Different,Count of Safety Measures Worse,READM Group Measure Count,Count of Facility READM Measures,Count of READM Measures Better,Count of READM Measures No Different,Count of READM Measures Worse,Pt Exp Group Measure Count,Count of Facility Pt Exp Measures,TE Group Measure Count,Count of Facility TE Measures
0,4,8,8,0,8,0,8,7,3,4,0,11,11,1,9,1,15,15,10,10
1,3,8,6,0,5,1,8,7,0,7,0,11,9,1,8,0,15,15,10,10
2,2,8,8,0,5,3,8,8,4,4,0,11,9,1,8,0,15,15,10,9
3,1,8,4,0,3,1,8,2,0,2,0,11,5,0,3,2,15,5,10,7
4,3,8,8,0,8,0,8,7,1,6,0,11,8,1,5,2,15,10,10,7

In [18]:
pd.to_numeric(..., errors="coerce")

ValueError: Buffer has wrong number of dimensions (expected 1, got 0)

In [19]:
for col in numeric_candidates:
    df_clean[col] = pd.to_numeric(df_clean[col], errors="coerce")

print("Conversion completed successfully.")

Conversion completed successfully.

In [20]:
df_clean[numeric_candidates].dtypes

Hospital overall rating                  float64
MORT Group Measure Count                 float64
Count of Facility MORT Measures          float64
Count of MORT Measures Better            float64
Count of MORT Measures No Different      float64
Count of MORT Measures Worse             float64
Safety Group Measure Count               float64
Count of Facility Safety Measures        float64
Count of Safety Measures Better          float64
Count of Safety Measures No Different    float64
Count of Safety Measures Worse           float64
READM Group Measure Count                float64
Count of Facility READM Measures         float64
Count of READM Measures Better           float64
Count of READM Measures No Different     float64
Count of READM Measures Worse            float64
Pt Exp Group Measure Count               float64
Count of Facility Pt Exp Measures        float64
TE Group Measure Count                   float64
Count of Facility TE Measures            float64
dtype: object

In [21]:
df_clean["Hospital overall rating"].value_counts(
    dropna=False
).sort_index()

Hospital overall rating
1.0     198
2.0     661
3.0     985
4.0     946
5.0     384
NaN    2245
Name: count, dtype: int64

In [22]:
df_clean["MORT Group Measure Count"].value_counts(
    dropna=False
).sort_index()

MORT Group Measure Count
8.0    4569
NaN     850
Name: count, dtype: int64

In [23]:
df_clean["ZIP Code"] = (
    df_clean["ZIP Code"]
    .astype(str)
    .str.zfill(5)
)

print("ZIP Code type:", df_clean["ZIP Code"].dtype)
df_clean["ZIP Code"].head(10)

ZIP Code type: str

0    36301
1    35957
2    35630
3    36467
4    35235
5    35968
6    35007
7    35660
8    36360
9    35960
Name: ZIP Code, dtype: str

In [24]:
missing_values = df_clean.isna().sum()

missing_values[missing_values > 0].sort_values(ascending=False)

TE Group Footnote                                   4411
READM Group Footnote                                4196
MORT Group Footnote                                 4023
Pt Exp Group Footnote                               3403
Safety Group Footnote                               3270
Meets criteria for birthing friendly designation    3156
Hospital overall rating footnote                    3103
Hospital overall rating                             2245
Count of Facility Safety Measures                   2075
Count of Safety Measures Better                     2075
Count of Safety Measures No Different               2075
Count of Safety Measures Worse                      2075
Count of Facility Pt Exp Measures                   1955
Count of MORT Measures Better                       1323
Count of Facility MORT Measures                     1323
Count of MORT Measures No Different                 1323
Count of MORT Measures Worse                        1323
Count of READM Measures Worse                       1155
Count of READM Measures No Different                1155
Count of READM Measures Better                      1155
Count of Facility READM Measures                    1155
Count of Facility TE Measures                        919
MORT Group Measure Count                             850
Safety Group Measure Count                           850
READM Group Measure Count                            850
Pt Exp Group Measure Count                           850
TE Group Measure Count                               850
dtype: int64

In [25]:
print("Rows:", df_clean.shape[0])
print("Columns:", df_clean.shape[1])
print("Duplicate rows:", df_clean.duplicated().sum())
print("Duplicate Facility IDs:", df_clean["Facility ID"].duplicated().sum())
print("Missing Facility IDs:", df_clean["Facility ID"].isna().sum())
print("Missing Facility Names:", df_clean["Facility Name"].isna().sum())

Rows: 5419
Columns: 38
Duplicate rows: 0
Duplicate Facility IDs: 0
Missing Facility IDs: 0
Missing Facility Names: 0

In [26]:
df_clean["ZIP Code"].str.len().value_counts()

ZIP Code
5    5419
Name: count, dtype: int64

In [27]:
df_clean.to_csv(
    "Hospital_General_Information_Cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully.")
print("Final shape:", df_clean.shape)

Cleaned dataset saved successfully.
Final shape: (5419, 38)